# 3. Escribe un programa en Python para dibujar un cohete. Aquí está el mío. ¡haz el tuyo diferente!

print("  ^^")
print(" <-->")
print("<---->")
print("|====|")
print("|----|")
print("|    |")
print("|><><|")
print("|    |")
print("|<<>>|")
print("======")
print("|====|")
print("|----|")
print("|    |")
print("|><><|")
print("|    |")
print("******")
print("******")
