---
title: "Ejercicios Capitulo 7"
author: "Christian Limbert Paredes Aguilera"
date: "2022-11-21"
output: pdf_document
---

# Ejercicios capitulo 7

## 7.1 
Una forma de mercadotecnia envía un cuestionario a $1000$ residentes de cierto suburbio de una ciudad para determinar sus preferencias como compradores. De los $1000$ residentes, $80$ responden el cuestionario. ¿Lo anterior constituye una muestra aleatoria? Discutir los méritos de este procedimiento para obtener una muestra aleatoria.

## 7.2
En una planta de armado automotriz se seleccionarán $50$ de los primeros $1000$ automóviles de un nuevo modelo para ser inspeccionados por el departamento de control de calidad. El gerente de la planta decide inspeccionar un automóvil cada vez que terminan de armarse $20$. ¿Este proceso dará como resultado una muestra aleatoria? Comente.

Respuesta.- Dado que el experimento se repite bajo las mismas condiciones, con variables aleatorias independientes e idénticamente distribuidas. Podemos decir que este experimento podría ser sin sesgo.

## 7.3
Si $X_1,X_2,\ldots,X_n$ constituye una muestra aleatoria, obtener las funciones de verosimilitud de las siguientes distribuciones:

### a)
De Poisson, con parámetro $\lambda$;

Respuesta.- Sea $p(x,\lambda)=\dfrac{e^{-\lambda}\lambda^x}{x}$ para $x=0,1,2,\ldots$, entonces la función de verosimilitud será
$$L(x_1,x_2,\ldots x_n)=\prod_{i=1}^n \dfrac{e^{-\lambda}\lambda^{x_i}}{x_i!}=\dfrac{e^{-\lambda}\lambda^{x_1}}{x_1!}\cdot \dfrac{e^{-\lambda}\lambda^{x_2}}{x_2!}\cdots \dfrac{e^{-\lambda}\lambda^{x_n}}{x_n!}=\dfrac{e^{-n\lambda}\lambda^{\sum_{i=1}^n x_i}}{\prod\limits_{i=1}^n x_i!},\; x=1,2,\ldots$$

### b)
Hipergeométrica, con parámetro $p$;

Respuesta.- Si  p = k/N, puede escribirse la función de probabilidad hipergeométrica como una función de probabilidad binomial y dado que el único parámetro es $p$ entonces,  $p(x,n,p)=\dfrac{n!}{(n-x)!x!} p^x(1-p)^{n-x},\; x=0,1,2,\ldots$


### c)
Uniforme en el intervalo $(a,b)$;

Respuesta.- Sea $\dfrac{1}{b-a}$ para $a\leq x \leq b$ una función de densidad de probabilidad uniforme. Entonces, la función de verosimilitud será:

$$L(x_1,x_2,\ldots,x_n)=\prod_{i=1}^n \dfrac{1}{b-a}=\dfrac{1}{b-a}\cdot\dfrac{1}{b-a}\cdot\cdots \dfrac{1}{b-a}=\dfrac{1}{(b-a)^n}$$

### d)
$N(\mu,\sigma)$

Respuesta.- Sea $f(x;\mu,\sigma)=\dfrac{1}{\sqrt{2\pi}{\sigma}}e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2}$, la función de densidad de probabilidad. Entonces la función de verosimilitud será:
$$\begin{array}{rcl}
  L(x_1,x_2,\ldots x_n;\mu,\sigma)&=&\prod\limits_{i=1}^n \dfrac{1}{\sqrt{2\pi}{\sigma}}e^{-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2}\\\\
  &=&\dfrac{1}{\sqrt{2\pi}{\sigma}}e^{-\frac{1}{2}\left(\frac{x_1-\mu}{\sigma}\right)^2}\cdot \dfrac{1}{\sqrt{2\pi}{\sigma}}e^{-\frac{1}{2}\left(\frac{x_2-\mu}{\sigma}\right)^2} \cdots \dfrac{1}{\sqrt{2\pi}{\sigma}}e^{-\frac{1}{2}\left(\frac{x_n-\mu}{\sigma}\right)^2}\\\\
  &=&\left(\dfrac{1}{\sqrt{2\pi}\sigma}\right)^n e^{-\sum \left[\frac{(x_i-\mu)^2}{2\sigma^2}\right]}
\end{array}$$


## 7.4
Repetir el ejercicio 7.3 para las siguientes distribuciones:

### a)
Gama con parámetro $\alpha$ y $\theta$.

Respuesta.- Sea, $\dfrac{1}{\Gamma(\alpha)\theta^{\alpha}}x^{\alpha-1}e^{-x/\theta}$ la distribución de densidad gama, entonces la función de verosimilitud será:

$$\begin{array}{rcl}
  L(x_1,x_2,\ldots x_n;\alpha,\theta)&=&\prod\limits_{i=1}^n \dfrac{1}{\Gamma(\alpha)\theta^{\alpha}}x^{\alpha-1}e^{-x_i/\theta}\\\\
  &=& \dfrac{1}{\Gamma(\alpha)\theta^{\alpha}}x^{\alpha-1}e^{-x_1/\theta}\cdot  \dfrac{1}{\Gamma(\alpha)\theta^{\alpha}}x^{\alpha-1}e^{-x_2/\theta} \cdots \dfrac{1}{\Gamma(\alpha)\theta^{\alpha}}x^{\alpha-1}e^{-x_n/\theta}\\\\
  &=& \left(\dfrac{x^{\alpha-1}}{\Gamma(\alpha)\theta^{\alpha}}\right)^n \cdot e^{\left(-\sum\limits_{i=1}^n\frac{x_i}{\theta}\right)}.
\end{array}$$



### b)
Weibull con parámetro $\alpha$ y $\theta$.

Respuesta.- Sea $f(x;\alpha,\theta)=\dfrac{\alpha}{\theta^{\alpha}}x^{\alpha-1}e^{-(x/\theta)^\alpha}$ la distribución de densidad de probabilidad Weibull, entonces la función de verosimilitud sera:

$$\begin{array}{rcl}
  L(x_1,x_2,\ldots x_n;\alpha,\theta)&=&\prod\limits_{i=1}^n \dfrac{\alpha}{\theta^{\alpha}}x_i^{\alpha-1}e^{-(x_i/\theta)^\alpha}\\\\
  &=&\dfrac{\alpha}{\theta^{\alpha}}x_1^{\alpha-1}e^{-(x_1/\theta)^\alpha}\cdot \dfrac{\alpha}{\theta^{\alpha}}x_2^{\alpha-1}e^{-(x_2/\theta)^\alpha}\cdots \dfrac{\alpha}{\theta^{\alpha}}x_n^{\alpha-1}e^{-(x_n/\theta)^\alpha}\\\\
  &=&\left(\dfrac{\alpha}{\theta^{\alpha}}\right)^n\cdot \prod\limits_{i=1}^n x_i^{\alpha-1}\cdot e^{\left[-\sum\limits_{i=1}^n \left(\frac{x_i}{\theta}\right)^\alpha\right]}.
\end{array}$$

## 7.5
Sea $X_1,X_2,\ldots,X_n$ una muestra aleatoria de una población cuya distribución es normal con media $\mu$ y varianza $\sigma^2$. De las siguientes, ¿cuáles son estadísticas?

### a)
$\sum X_i-\mu$.

Respuesta.- No es estadística ya que no está definida $X_i$ ni se conoce el valor de $\mu$.

### b)
$\sigma X_1 + \sigma X_2$.

Respuesta.- No es estadística ya que no se conoce el valor de sigma.

### c)
$X_i,i=1,2,\ldots,n$.

Respuesta.- Es estadística porque $X_i$ está definida entre $1$ y $n$.

### d)
$X_1^2+X_2^2 - e^{X_3}$.

Respuesta.- Es estadística.

### e)
$\dfrac{X_i}{\sigma},\; i=1,2,\ldots, n$.

Respuesta.- No es estadística porque no se conoce el valor de $\sigma$.

### f)
$\sum \left(X_i-\overline{X}\right)^2$.

Respuesta.- Es estadística porque es una función completa.


## 7.6
Sean $X_1,X_2,\ldots,X_n$ $n$ variables aleatorias independientes de Poisson con parámetros $\lambda_1,\lambda_2,\ldots,\lambda_n$ respectivamente. Mediante el empleo de la función generadora de momentos, demostrar que la suma de estas variables también es una variable aleatoria de Poisson con parámetros $\lambda_1+\lambda_2+\cdots + \lambda_n$.

Respuesta.- Sea,
$$m_{X_i}(t)=e^{\lambda_i(e^t-1)}$$
la función generadora de momentos de la distribución Poisson, entonces por el teorema 7.1, con $a_i=1$. La suma de las variables también es una variable aleatoria de Poisson. Es decir, sea 
$$Y=X_1+X_2+\ldots + X_n$$
de donde,
$$
\begin{array}{rcl}
  m_{Y}(t)&=&m_{X_1}(t)m_{X_2}(t)\cdots m_{X_n}(t)\\\\
  &=& e^{\lambda_1\left(e^t-1\right)}e^{\lambda_2\left(e^t-1\right)}\cdots e^{\lambda_n(e^t-1)}\\\\
  &=& e^{\left[\lambda_1\left(e^t-1\right)+\lambda_2\left(e^t-1\right)+\ldots+ \lambda_n\left(e^t-1\right) \right]}\\\\
  &=& e^{\left[\left(\lambda_1+\lambda_2+\ldots + \lambda_n\right)\left(e^t-1\right)\right]} 
\end{array}
$$

## 7.7
Sean $X_1$ y $X_2$ dos variables aleatorias independientes de Poisson con parámetros $\lambda_1$ y $\lambda_2$, respectivamente. Demostrar que la diferencia entre $X_1$ y $X_2$ no es una variable aleatoria de Poisson.

Respuesta.- Sea,
$$Y=X_1-X_2$$
Entonces por el teorema 7.1 con $a_i=1$, 

$$
\begin{array}{rcl}
  m_Y(t) &=& E\left\{e^{\left[t(X_1-X_2)\right]}\right\}\\\\
  &=& E\left\{\dfrac{e^{t(X_1)}}{e^{t(X_2)}}\right\}\\\\
  &=& \dfrac{E\left\{e^{t(X_1)}\right\}}{E\left\{e^{t(X_2)}\right\}}\\\\
  &=& \dfrac{m_{X_1}(t)}{m_{X_2}(t)}\\\\
  &=& \dfrac{e^{\lambda_1(e^x-1)}}{e^{\lambda_2(e^x-1)}}
\end{array}
$$

## 7.8
Sean $X_1$ y $X_2$ dos variables aleatorias independientes binomial con parámetros $n_1$ y $p$, y $n_2$ y $p$, respectivamente. Demostrar que la suma  de $X_1$ y $X_2$ es una variable aleatoria binomial con parámetros $n_1+n_2$ y $p$.

Respuesta.-


## 7.9
Sean $X_1$ y $X_2$ dos variables aleatorias independientes distribuidas exponencialmente con el miemos parámetro $\theta$. Demostrar que la suma de $X_1$ y $X_2$ es una variable aleatoria gama con parámetros de forma $2$ y parámetro de escala $\theta$.

Respuesta.-

## 7.10
Para un determinado nivel de ingresos, el Departamento de Hacienda sabe que las cantidades declaradas por concepto de deducciones médicas $(X_1)$, contribuciones caritativas $(X_2)$ y gastos varios $(X_3)$, son variables aleatorias independientes normalmente distribuidas con media $\$ 400, \$ 800$ y $\$100$ y desviaciones estándar $\&100, \$ 250$ y $\$40$, respectivamente.

### a)
¿Cuàl es la probabilidad de que la cantidad total declarada por concepto de estas tres deducciones, no sea mayor de $\$1600$?

Respuesta.-

### b)
Si una persona con este nivel de ingresos declara por concepto de estas deducciones un total de $\$ 2100$, ¿qué tan probable es tener una cantidad igual o mayor a este monto bajo las condiciones dadas?

Respuesta.-


## 7.11
Una tienda de artículos eléctronicos para el hogar vende tres diferentes marcas de refrigeradores. Sean $X_1,X_2$ y $X_3$ variables aleatorias las cuales representan el volumen de ventas mensuales para cada una de las tres marcas de refrigeradores. Si $X_1,X_2$ y $X_3$ son variables aleatorias independientes normalmente distribuidas con medias $\$ 8000$, $\$15000$ y $\$12000$, y desviación estándar $\$2000$ $\$5000$ y $\$3000$, respectivamente, obtener la probabilidad de que, para un mes en particular, el volumen de venta total para los tres refrigeradores sea mayor de $\$50000$.

Respuesta.-


## 7.12
En una tienda de servicio el tiempo total del sistema consta de dos componentes (el lapso de tiempo que de esperar para que el servicio de comiento $(X_1)$ y el lapso de tiempo que este dura $(X_2)$). Si $X_1$ y $X_2$ son variables aleatorias independientes exponencialemente distribuidas con un tiempo medio de $4$ minutos cada una, ¿cuál es la probabilidad de que el tiempo total que tarda el sistema en proporcionar el servicio no sea mayor de $15$ minutos? (Sugerencia: consulte el ejercicio 7.9.)

Respuesta.-


## 7.13 
Sea $X_1,X_2,\ldots, X_n$ una muestra aleatoria de una población que tiene una distribución gama con parámetros $\alpha$ y $\theta$. Mediante el uso de la función generadora de momentos, demostrar que la distribución dela media muestral $\overline{X}$ también es de tipo gama, con parámetros de escala y de forma iguales a $n\alpha$ y $\theta/n$ respectivamente.

Respuesta.-


## 7.14
Miediante el emeplo de los resultados de la sección 5.9, generar números aleatorios para las distribuciones binomial y exponencial y usarlos para demostrar el teorema central del límite. De manera específica, para $n=10$ y $n=40$, generar $50$ muestras de una distribución binomial con $p=0.4$. Repetir el procedimiento anterior generando $50$ muestras de una distribución exponencial con parámetro $\theta=100$. ¿Se ha demostrado el teorema central del límite en un grado razonable?.

Respuesta.-


## 7.15
Para cierta prueba de aptitud se sabe con base a la experiencia que el número e aciertos es $1000$ con una desviación estándar de $126$. Si se aplica la prueba a $100$ personas seleccionadas al azar, aproximar las siguientes probabilidades que involucran a la media muestra $\overline{X}$.

### a)
$P\left(985<\overline{X}<1015\right)$

Respuesta.-

### b)
$P\left(960<\overline{X}<1040\right)$

Respuesta.-

### c)
$P\left(\overline{X}>1020\right)$

Respuesta.-

### d)
$P\left(\overline{X}<975\right)$

Respuesta.-


## 7.16
Una contratista piensa comprar una gran cantidad de lámparas de alta intensidad a cierto fabricante. Este asegura al contratista que la duración promedio de las lámparas es de $1000$ horas con una desviación estándar igual a $80$ horas: El contratista decide comprar las lámparas sólo si una muestra aleatoria de $64$ de estas da como resultado una vida promedio de por lo menos $1000$ horas. ¿Cuàl es la probabilidad de que el contratista adquiera las lámparas?

Respuesta.-


## 7.17
Un inspector federal de pesos y medidas visita una planta de empacado para verificar que el peso neto de las cajas sea el indicado en estas. El genente de la planta asegura al inspector que el peso promedio de cada caja es de $750$ gr. con una desviación estándar de $5$ gr. Bajo estas condiciones, ¿què tan probable es tener un peso de $748$ o menos? ¿Qué actitud debe tomar el inspector?

Respuesta.-\; 


## 7.18
En la fabricación de cojinetes para motores, se sabe que el diámetro es de $5$ cm. con una desviación estándar igual a $0.005$ cm. El preceso es vigilado en forma periódica mediante la selección aleatoria de $64$ cojinetes, midiendo sus correspondientes diámetros. EL proceso no se detiene mientras la probabilidad de que la media muestral se encuentre entre dos límites especificados sea de $0.95$. Determinar el valor de estos límites.

Respuesta.-


## 7.19
En la producción de cierto material para soldar se sabe que la desviación estándar de a tensión de ruptura de este material de $25$ libras. ¿Cuál debe ser la tensión de ruptura promedio del proceso si, con base en una muestra aleatoria de $50$ especímenes, la probalidad de que la media muestral tenga un valor mayor que $250$ libras es de $0.95$?

Respuesta.-


## 7.20
Genere $50$ muestras, cada una de tamaño $25$ a partir de una distribución normal con media $60$ y desviación estándar $10$. Calcule la varianza de cada muestra mediante el empleo de (7.14).

### a)
Obtener la media y la varianza de $S^2$ mediante el empleo de los $50$ valores calculados. ¿Cómo son estos valores al compararlos con los proporcionados por las extensiones (7.17) y (7.18)?.

Respuesta.-

### b)
Agrupar los $50$ valores calculados de $S^2$ y graficar las frecuencias relativas. Coméntese sobre los resultados.

Respuesta.-




