---
title: 'Nivel avanzado: Variables aleatorias. Complementos'
author: "Christian Limbert Paredes Aguilera"
date: "25/1/2022"
output: html_document
---

# Momentos de orden n
Sea $X$ una variable aleatoria. Definimos el momento de orden $n$ como $m_n = E(X^n)$

El momento de orden $1$ de una variable aleatorio es su valor medio o $E(X).$

Los momentos de orden $n$ caracterizan una variable $X$. O sea, que si conocemos todos los momentos de orden $n$, podemos deducir cuál es la distribución de $X$.

## Momoentos centrales de orden n de una variable aleatoria
Sea $X$ una variable aleatoria. Definimos el momento central de orden $n$ como $\mu_n = E[(X--\mu)^n]$, donde $\mu=E(X)$ es la media o esperanza de la variables aleatoria $X$.

El momento central de orden 1 de una v.a. es siempre 0.
$$\mu_1 = E_1(X-\mu) = E(X)-E(\mu)=E(X)-E(X)=0$$

El momento central de orden 2 de una v.a. es la varianza
$$\mu_2 = E(X-\mu)^2 = Var(X)$$

Los momentos centrales de orden $n$ caracterizan también una variable $X$. O sea, que si conocemos todos los momentos centrales de orden $n$, podemos deducir cuál es la distribución de $X$.

#### Propocisión 
La relación que hay entre los momentos centrales y los momentos de una v.a. es la siguiente:
$$\mu_n = \sum_{k=0}^n (-1)^{n-k}{n\choose k} \mu^{n-k}m_k = \sum_{k=0}^n (-1)^k{n \choose k}\mu^k m_{n-k}$$
donde $\mu=E(X)$ recordemos que es la esperanza de la v.a. X.

Demostración.-\; Recordemos la definición de momentos centrales de orden $n$ y desarrollemos aplicando el binomio de Newton:
$$\mu_n = E(X-\mu) = E\left(\sum_{k=0}^n (-1)^{n-k}{n \choose k} x^k \mu^{n-k}\right)$$

La esperanza de la suma es la suma de esperanzas, obtenemos la expresión dada por la proposición:
$$\mu_n = \sum_{k=0}^n (-1)^{n-k} E(X^k)=\sum_{k=0}^n (-1)^{n-k}{n\choose k}\mu^{n-k}m_k$$

## Asimetría de una variable aleatoria
Una variable aleatoria tiene asimetría positiva si su función de densidad o de probabilidad presenta una cola a la derecha y asimetría negativa, si su función de densidad o de probabilidad presenta cola a la izquierda.

### ¿Cómo calcular la asimetría de una variable aleatoria?

#### Coeficiente de asimetría de Pearson
La simetría de una variable aleatoria $X$ se calcula a partir de sus momentos centrales de segundo y tercer orden:
$$\gamma = E \left(\dfrac{X-\mu}{\sigma} \right)^3 = \dfrac{\mu_3}{\sigma^3}$$

donde $\mu=E(X)$ y $\sigma^2 = Var(X)$

### Coeficiente de asimetría
$$\gamma_1 = \dfrac{m_3 - 3\mu\sigma^2 - \mu^3}{\sigma^3}$$

Por tanto, una variable aleatoria $X$ tendrá simetría positiva o a la derecha si   $\gamma_1>0$ y tendrá asimetría negativa o a la izquierda, si $\gamma_1<0$.

## Curtosis o apuntamiento de una variable aleatoria

### Medida de curtosis de Pearson
La manera estándard de medir la curtosis de una variable aleatoria $X$ es a partir de su momento central de cuarto orden:
$$\gamma^2 = E\left(\dfrac{X-\mu}{\sigma}\right)^4=\dfrac{\mu_4}{\sigma^4}$$


-  Diremos que una variable aleatoria no tiene exceso de curtosis o mesocúrtica si $\gamma_2=3.$

- Diremos que una variable aleatoria tiene exceso positivo de curtosis o leptocúrtica si $\gamma_2>3.$

- Diremos que una variable aleatoria tiene exceso negativo de curtosis o platicúrtica si $\gamma_2<3.$


# Función generadora de momentos
Sea $X$ una v.a. $X$ con función de probabilidad $P_X$ en el caso discreto o función de densidad $f_X$ en el caso continuo.

Sea $t\in \mathbb{R}$ un valor real cualquiera. Definimos la función generatriz de momentos $m_X(t)$ en el valor $t$ como:
$$m_X(t)=E(e^{tX})$$

## Cómo calcular los momentos a partir de la función generatriz
### Relación entre la función generatriz de momentos y los momentos

#### Proposición 
Sean $X$ una variable aleatoria con función generatriz de momentos $m_x(t)$. Entonces, el momento de orden $n$ de $X$ se puede obtener de la forma siguiente:
$$m_n = E(X^n) = \dfrac{d}{dt^n}m_X(t)\bigg|_{t=0} = m_X^{(n)}(0).$$

O sea, el momento de orden $n$ de $X$ es la derivada n-ésima de la función generatriz de momentos evaluada en $t=0$.

Demostración.- Recordemos la definición de la función generatriz de momentos: $$M_X(t)=E(e^{tX}).$$

la idea de la demostración es probar por inducción que $m_X^{(n)}(t)$

Veámoslo para $n=1$; $m^{'}_X(t) = E(e^{tX}X)$

Seguidamente, apliquemos inducción sobre $n$. Supongamos que $m_X^{(n)}(t)=E(e^{tX}X^n)$ y veamos que $m_X^{n+1}(t)=E(e^{tX}X^{n+1}): m_X^{n+1}(t) = \dfrac{d}{dt}(m_X^{(n)}X^n) = E(e^{tX}X^{n+1})$ tal como queriamos demostar.

Por último apliquemos la expresión demostrada $m_X^{(n)}=E(e^{tX}X^n)$ a $t=0$, obtenemos: $m_X^{(n)}(0) = E(X^n) = m_n$ tal como dice la proposición.

## Función característica de una variable aleatoria
### Definición

Sea $X$ una variable aleatoria $X$ con función de probabilidad $P_X$ en el caso discreto o función de densidad $f_X$ en el caso continuo.

Sea $w\in \mathbb{R}$ un valor real cualquiera.

Definimos la función característica $\phi_X(w)$ en el valor $w$ como:

$\phi_X(w) = E(e^{iwX})$, donde $i$ es el número complejo $i=\sqrt{-1}$

#### Observaciones
Si $X$ es una variable aleatoria continua, la función caracteristica $\phi_X(w)$ puede interpretarse como la transformada de Fourier de la función de densidad de $X$:
$$\phi(w) = \int_{-\infty}^\infty f_X(x)e^{iwx}\; dx$$

Por lo tanto, usando la fórmula de la antitransformada de Fourier, podemos escribir la función de densidad $f_X(x)$ como función de la función característica de $X$

$$\phi_X(x): \; f_X(x) = \dfrac{1}{2\pi}\int_{-\infty}^{\infty}\phi_X(w)e^{-iwx}\; dw$$

En el caso discreto, o sea, si $X$ es una variable discreta, la función característica $\phi_X(w)$ se escribe como función de la función de probabilidad $P_X(x_k)$ con dominio $D_X = \lbrace x_k,k\rbrace$ como: $\phi(w)\sum_k P_X(x_k)e^{iwk}.$

En los casos en que los $x_k$ sean enteros, $x_k=k$, que son la mayoría, la ecuación anterior en la transformada de Fourier de la secuencia $P_X(k)$. Dicha función es una función periódica en $w$ de periodo $2\pi$ ya que $e^{i(w+2\pi)k}=e^{iwk}.$

Por tanto, usando la fórmula de inversión, podemos escribir la función de probabilidad $P_X(k)$ como función de la función característica de $X$, $\phi(w)$:
$$P_X(k)=\dfrac{1}{2\pi}\int_0^{2\pi}\phi(w)e^{-iwk}\; dw$$

## Cómo calcular los momentos a partir de una función característica.
