---
title: "Vectores aleatorios bidimensionales"
author: "Christian Limbert Paredes Aguilera"
date: "16/2/2022"
output: pdf_document
---
# Vectores aleatorios bidimencionales 

## Variables aleatorias bidimencionales
Redordemos que una variable aleatoria $X$ es una aplicación que toma valores numéricos para cada resultado de un experimento aleatorio:
$$\begin{array}{rcl}
  X:\Omega&\longrightarrow&\mathbb{R}\\
  w&\longrightarrow&X(w)\\
\end{array}$$

A partir de la definición anterior, generalizamos la noción de variable aleatoria unidimencional a variable aleatoria bidimencional.

### Definición de variable aleatoria bidimencional
Dado un experimentos aleatorio con espacio muestral $\Omega$, definimos variable aleatoria bidimencional $(X,Y)$ a toda aplicación 
$$\begin{array}{rcl}
  X:\Omega&\longrightarrow&\mathbb{R}^2\\
  w&\longrightarrow&(X(w),Y(w))\\
\end{array}$$

La probabilidad de que la variable bidimencional pertenezca a una cierta región del plano $B$ se define de la forma siguiente:
$$P((X,Y)\in B)=P\lbrace w\in \Omega,\; | \; (X(w),Y(w))\in B\rbrace$$

o sea, la probabilidad anterior es la probabilidad del suceso formado por los elementos de $w\in \Omega$ que cumplen que su imagen por la variable aleatoria bidimencional $(X,Y)$ esté en $B$.

## Función de distribución conjunta

### Definición de función de distribución conjunta: 
Dada una variable bidimencional $(X,Y)$, definimos su función de distribución conjunta $F_{XY}$ a la función definida sobre $\mathbb{R}^2$ de la manera siguiente:

$$\begin{array}{rcl}
  F_{XY}:\mathbb{R}^2&\longrightarrow&\mathbb{R}\\
  (x,y)&\longrightarrow&F_{XY}(x,y)=P(X\leq x, Y\leq y)\\
\end{array}$$

 Se buscará que tan probable será que un punto caiga en una región del plano cartesiano.
 
Entonces la función de distribución conjunta en el valor $(x,y)$ es la probabilidad del suceso formado por aquellos elementos tal que la imagen por la variable aleatoria bidimensional $(X,Y)$ caen dentro de la región sombreada en el gráfico anterior:

$$F_{XY}(x,y)=P\lbrace w\in \Omega | (X(w),Y(w)) \in (-\infty,x]\times (-\infty,y]) \rbrace = P\lbrace w \in \Omega | X(w)\leq Y(w)\leq y\rbrace$$

#### Propiedades
Sea $(X,Y)$ una variable bidimensional. Sean $F_{XY}$ su función de distribución conjunta. Dicha función satisface las propiedades siguientes:

- La función de distribución conjunta es no decreciente en cada una de las variables:
$$\mbox{Si}\;  x_1\leq x_2,\; y\; y_1\leq y_2,\; \mbox{entonces}\; F_{XY}(x_1,y_1)\leq F_{XY}(x_2,y_2).$$

- $F_{XY}(x,-\infty)=F_{XY}(-\infty,y)=0,\; F_{XY}(\infty,\infty)=1$ para todo $x,y\in \mathbb{R}$.

- Las variables aleatorias $X$ e $Y$ se llaman variables aleatorias marginales y sus funciones de distribución $F_X$ y $F_Y$ pueden hallarse de la forma siguiente como función de la función de distribución conjunta $F_{XY}$:
$$F_X(x)=F_{XY}(x,\infty),\; F_Y(y)=F_{XY}(\infty.y),$$
para todo $x,y \in \mathbb{R}$

- La función de distribución conjunta es continua por el norte y por el este:
$$\lim_{x\to a^+}F_{XY}(x,y)=\lim_{x\to a, x>a}F_{XY}(x,y)=F_{XY}(a,y),$$
$$\lim_{x\to b^+}F_{XY}(x,y)=\lim_{x\to b, x>b} F_{XY}(x,y)=F_{XY}(x,b),$$
para todo $a,b \in \mathbb{R}$.

- Dados $x_1<x_2$ e $y_1<y_2$, consideramos $B$ el rectángulo de vértices $(x_1,y_1)$, $(x_1,y_2)$, $(x_2,y_1)$ y $(x_2,y_2)$: $(x_1,y_2]\times (y_1,y_2]$. Entonces,
$$P((X,Y)\in B)=F_{XY}(x_2,y_2)-F_{XY}(x_2,y_1)-F_{XY}(x_1,y_2)+F_{XY}(x_1,y_1)$$

## Variables bidimensionlaes discretas.

La función pdado devuelve la probabilidad de que salga la cara $x$ en un dado de $n$ caras donde por defecto $n=6$.

```{r}
pdado = function(x,n=6) sapply(x,FUN = function(x)
  if(x %in% c(1:n)) {return(1/n)} else {return(0)})
pdado(4,6)
```

## Propiedades de la función de probabilidad conjunta.

Sea $(X,Y)$ una variable aleatoria bidimensional discreta con conjunto de valores $(X,Y)(\Omega) = \lbrace (x_i, y_j) i = 1,2, \ldots, j = 1,2,\ldots \rbrace$ Entonces su función de probabilidad conjunta verifica las propiedades siguientes:

La suma de todos los valores de la función de probabilidad conjunta sobre el conjunto de valores siempre vale 1:

$$\sum_i \sum_j P_{XY}(x_i,y_j)=1$$

En particular sea $B$ una región del plano. El valor de la probabilidad $P((X,Y)\in B)$ se puede calcular de ña forma siguiente:
$$P((X,Y)\in B) = \sum_{(x_i.y_j)\in B} P_{XY}(x_i,y_j)$$

O sea, la probabilidad de que la variable bidimensional coja valores en $B$ es igual a la suma de todos aquellos valores de la función de probabilidad conjunta que están en $B$.

Luego tenemos la realación siguiente que relaciona la función de distribución conjunta con la función de probabilidad conjunta:
$$F_{XY}(x,y) = \sum_{x_i\leq x, y_j\leq y} P_{XY}(x_i.y_j).$$
Dicha expresión se deduce de la expresión anterior considerando  $B=(-\infty,x]\times (-\infty,y]$

## Las variables marginales
Consideremos una variable aleatoria bidimensional discreta $(X,Y)$ con función de probabilidad conjunta $P_{XY}(x_i,y_i)$, con $x_i,y_i \in (X,Y)(\Omega), i=1,2,\ldots,\; j=1,2,\ldots$.

Donde $P_X$ y $P_Y$ llamadas distribuciones marginales se pueden obtener de la tabla $P_{XY}$

### Proposición. Expresión de las funciones de probabilidad marginales.

Sea $(X,Y)$ una variable aleatoria bidimensional discreta con función de probabilidad conjunta $P_{XY}(x_i,y_i)$, con $(x_i,y_i)\in (X,Y)(\Omega), \; i = 1,\ldots, n,\; j=1,\ldots,m$

Las funciones de probabilidad marginales $P_X(x_i)$ y $P_Y(y_j)$ se calculan usando las expresiones siguientes:

$$\begin{array}{rcl}
P_X(x_i)&=&\sum_{j=1} P_{XY}(x_i,y_j),\; i=1,2,\ldots,\\\\
P_Y(y_j)&=&\sum_{i=1} P_{XY}(x_i,y_j),\; j=1,2,\ldots,\\
\end{array}$$

Para obtener la función de probabilidad marginal de la variable $X$ en el valor $x_i$, $P_X(x_i)$ hay que sumar todos los valores de $P_{XY}(x_i,y_j)$ correspondientes a la fila i-énesima y para obtener la función de probabilidad marginal de la variable $Y$ en el valor $y_j$, $P_Y(y_j)$ hay que sumar todos los valores de $P_{XY}(x_i.y_j)$ correspondientes a la columna j-ésima.


## Variables aleatorias continuas

### Definición de variable aleatoria bidimensional continua
Sea $(X,Y)$ una variable aleatoria bidimensional. Diremos que $(X,Y)$ es continua si existe una función $f_{XY}: \mathbb{R}^2 \longrightarrow \mathbb{R}$ llamada función de densidad no negativa $f_{XY}(x,y)\geq 0$ para todo $(x,y)\in \mathbb{R}^2$ tal que dado cualquier región $B$ del plano, la probabilidad de que $(X,Y)$ esté en $B$ se calcula de la forma siguiente:

$$P((X,Y)\in B) = \int\int_B f_{XY}(x,y)\; dx \,dy.$$

### Propiedades de la función de densidad
Sea $(X,Y)$ una variable aleatoria bidimensional continua con función de densidad $f_{XY}$. Entonces dicha función verifica las propiedades siguientes:

- La integral de dicha función sobre todo el plano vale 1:

$$\int\int_{\mathbb{R}^2} f_{XY} (x,y)\;dx\,dy = 1.$$

Para ver dicha propiedad, basta considerar $B=\mathbb{R}^2$, tener en cuenta que el suceso $(X,Y) \in \mathbb{R}^2$ es el total $\Omega$ y aplicar la definición de $f_{XY}$

$$P((X,Y)\in \mathbb{R}^2)=1=\int\int_{\mathbb{R}^2} f_{XY}(x,y)\; dx\, dy.$$

- La relación que hay entre la función de distribución $F_{XY}$ y la función de densidad $f_{XY}$ es la siguiente:

$$F_{XY}(x,y)=\int_{-\infty}^x \int_{-\infty}^y f_{XY}(u,y)\; du\, dv.$$

Para ver dicha propiedad, basta considerar $B=(-\infty,x]\times (-\infty,y]$ y aplicar la definción de función de distribución:
$$F_{XY}(x,y) = P((X,Y)\in (-\infty,x]\times (-\infty,y])=\int_{-\infty}^x \int_{-\infty}^y f_{XY}(u,v)\; du\, dv.$$

- La relación que hay entre la función de densidad $f_{XY}$ y la función de distribución $F_{XY}$ es la siguiente:

$$f_{XY}(x,y)=\dfrac{\partial^2 F_{XY}(x,y)}{\partial x \, \partial y}$$
dicha propiedad se deduce de la anterior, derivando primero respecto a $x$ y después respecto a $y$ para eliminar las dos integrales.

- Las funciones de densidad marginales de las variables $X$ e $Y$, $f_X,\, f_X(x)$ y $f_Y (y)$ respectivamente, se calculan de la forma siguiente:

$$f_X(x)=\int_{-\infty}^{\infty}f_{XY}(x,y)\; dy,\, f_Y(y)=\int_{-\infty}^{\infty}f_{XY}(x,y)\; dx$$

## La distribución normal bidimensional.

### Definición de distribución Gaussiana bidimensional
Diremos que la distribución de la variable aleatoria bidimensional $(X,Y)$ es gaussiana bidimensional dependiendo del parámetro $rho$ si su función de densidad conjunta es:

$$f_{XY}(x,y) = \dfrac{1}{2\pi \sqrt{1-\rho^2}} e^{-\frac{x^2-2\rho xy + y^2}{2(1-\rho^2)}}, \qquad -\infty < x,y < \infty.$$

### Propiedades

- Para cualquier punto $(x,y) \in \mathbb{R}^2$, la función de densidad es no nula: $f$_{XY}(x,y)>0.$

- La función de densidad tiene un único máximo absoluto en el punto $(0,0)$ que vale $f_{XY}(0,0)=\dfrac{1}{2\pi \sqrt{1-\rho^2}}.$ Por tanto, para $\rho=0$, dicho máximo alcanza el mínimo valor posible y su $p\to \pm 1$, dicho máximo tiende a $\infty$.

- Las densidades marginales $f_{X}(x)$ y $f_Y(y)$ son normales $N(0,1)$.

Demostración.-\; Veámoslo con $f_{X}(x).$ Por simetría, quedaría deducido para $f_Y(y)$:

$$\begin{array}{rcl}
  f_X(x) & = & \dfrac{1}{2\pi \sqrt{1-\rho^2}} \displaystyle \int_{-\infty}^{\infty} e^{-\frac{x^2-2\rho xy + y^2}{2(1-\rho^2)}} dy \\
  &=&\dfrac{1}{2\pi \sqrt{1-\rho^2}} e^{-\frac{x^2}{2(1-\rho^2)}}\displaystyle\int_{-\infty}^{\infty} e^{-\frac{-2\rho xy + y^2}{2(1-\rho^2)}} dy\\
  &=&\dfrac{1}{2\pi \sqrt{1-\rho^2}} e^{-\frac{x^2}{2(1-\rho^2)}}\displaystyle\int_{-\infty}^{\infty}e^{\frac{(y-\rho x)^2}{2(1-\rho^2)}}e^{\frac{\rho^2 x^2}{2(1-\rho^2)}} \;dy\\
  &=&\dfrac{1}{2\pi \sqrt{1-\rho^2}} e^{-\frac{x^2}{2}}\displaystyle\int_{-\infty}^\infty e^{-\frac{(y-\rho x)^2}{2(1-\rho^2)}}\; dy, \;\mbox{hacemos cambio}\; z=\dfrac{y-\rho x}{\sqrt{1-\rho^2}}\\
  &=&\dfrac{1}{2\pi \sqrt{1-\rho^2}} e^{-\frac{x^2}{2}}\displaystyle\int_{-\infty}^\infty e^{-\frac{z^2}{2}} \sqrt{1-\rho^2\; dy}\\
  &=&\dfrac{1}{\sqrt{2\pi}} e^{\frac{x^2}{2}}\\
\end{array}$$

función que coincide con la función de densidad de la variable $N(0,1).$

En el último paso hemos usado que 
$$\dfrac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} e^{-\frac{x^2}{2}}\; dz = 1.$$

Ya que correspondería al área de una función de densidad de una distribución $N(0,1)$

## Independencia de variables aleatorias discretas

### Definición de independencia para variables aleatorias bidimensionales discretas.

Sean $(X,Y)$ una variable aleatoria bidimensional discreta con $(X,Y)=\lbrace (x_i,y_j),\; i=1,2,\ldots, \; j=1,2,\ldots\rbrace$ y función de probabilidad $P_{XY}$ y funciones de probabilidad marginales $P_X$ y $P_Y$. Entonces $X$ e $Y$ son independientes si:
$$P_{XY}(x_i,y_i) = P_X(x_i)\cdot P_Y(y_k), \; i=1,2,\ldots,\; j=1,2,\ldots$$
o dicho de otra forma:

$$P(X=x_i,Y=y_k) = P(X=x_i)\cdot P(Y=y_j), \; i=1,2,\ldots,\; j=1,2,\ldots$$

#### Observación.-
Si la tabla de la función de probabilidad conjunta de $(X,Y)$ contiene algún $0$, $X$ e $Y$ no pueden ser independientes.


